variables:
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')] 
  - name: ServiceInfo__ReleaseVersion
    value: $(Build.BuildNumber)     

trigger:
  branches:
    include:
      - master

name: $(Date:yy).$(Month)$(DayOfYear).$(Rev:r)

pr:
  branches:
    include:
      - "master"
      - "feature/*"
      - "hotfix/*"
      - "bugfix/*"

pool:
  vmImage: "ubuntu-latest"


stages:
  - stage: Build
    jobs:
      - job: build_backend
        displayName: "Build web api"
        steps:
          - checkout: self
            submodules: recursive

          - task: UseDotNet@2
            displayName: "Install .NET SDK"
            inputs:
              packageType: "sdk"
              version: "9.0.x"

          - task: DotNetCoreCLI@2
            displayName: "Run .NET Unit Tests"
            inputs:
              command: "test"
              projects: "src/FishScraper.Core/FishScraper.Core.sln"
              arguments: "-c Release"

          - task: FileTransform@2
            displayName: "Transform all configuration files"
            inputs:
              enableXmlTransform: false
              fileType: "json"
              folderPath: "$(Build.SourcesDirectory)/src/FishScraper.Core/FishScraper.Core.Api"
              jsonTargetFiles: "appsettings.json" 
